import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';import {Button} from 'react-native';/**



 * Sample React Native App



 * https://github.com/facebook/react-native



 * @flow



 */







import React, { Component } from 'react';



import {



  AppRegistry,



  StyleSheet,



  Text,



  View



} from 'react-native';







export default class myAwesomeProject extends Component {



  render() {



    return (



      <View style={styles.container}>



        <Text style={styles.welcome}>



          Welcome to React Native!



        </Text>



        <Text style={styles.instructions}>



          To get started, edit index.android.js



        </Text>



        <Text style={styles.instructions}>



          Double tap R on your keyboard to reload,{'\n'}



          Shake or press menu button for dev menu



        </Text>



<Button onPress={() => {console.log("ceva") }} title="Mihai Button smecheru'" />
<Button onPress={() => {console.log("ceva") }} title="asasa" />
<Button onPress={() => {console.log("ceva") }} title="" />
<Button onPress={() => {console.log("ceva") }} title="" />
<Button onPress={() => {console.log("ceva") }} title="" />
<Button onPress={() => {console.log("ceva") }} title="edae" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="edas" />
<Button onPress={() => {console.log("ceva") }} title="asaa" />
<Button onPress={() => {console.log("ceva") }} title="gta" />
<Button onPress={() => {console.log("ceva") }} title="sss" />
<Button onPress={() => {console.log("ceva") }} title="fdf" />
<Button onPress={() => {console.log("ceva") }} title="dgfgd" />
<Button onPress={() => {console.log("ceva") }} title="aaaaaaa" />
<Button onPress={() => {console.log("ceva") }} title="sssss" />
<Button onPress={() => {console.log("ceva") }} title="asdasa" />
<Button onPress={() => {console.log("ceva") }} title="sadaad" />
<Button onPress={() => {console.log("ceva") }} title="asass" />
<Button onPress={() => {console.log("ceva") }} title="sadasd" />
<Button onPress={() => {console.log("ceva") }} title="saadsa" />
<Button onPress={() => {console.log("ceva") }} title="asas" />
<Button onPress={() => {console.log("ceva") }} title="sads" />
<Button onPress={() => {console.log("ceva") }} title="aaa" />
<Button onPress={() => {console.log("ceva") }} title="aa" />
<Button onPress={() => {console.log("ceva") }} title="aaa" />
<Button onPress={() => {console.log("ceva") }} title="asa" />
<Button onPress={() => {console.log("ceva") }} title="asa" />
<Button onPress={() => {console.log("ceva") }} title="sas" />
<Button onPress={() => {console.log("ceva") }} title="aaaa" />
<Button onPress={() => {console.log("ceva") }} title="aa" />
<Button onPress={() => {console.log("ceva") }} title="Button1" />
<Button onPress={() => {console.log("ceva") }} title="Button" />
      </View>



    );



  }



}







const styles = StyleSheet.create({



  container: {



    flex: 1,



    justifyContent: 'center',



    alignItems: 'center',



    backgroundColor: '#F5FCFF',



  },



  welcome: {



    fontSize: 20,



    textAlign: 'center',



    margin: 10,



  },



  instructions: {



    textAlign: 'center',



    color: '#333333',



    marginBottom: 5,



  },



});







AppRegistry.registerComponent('myAwesomeProject', () => myAwesomeProject);











































































































































































































































